nodeLinker: node-modules

npmScopes:
  flash-tecnologia:
    npmAlwaysAuth: true
    npmAuthToken: "${GH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
